development:
  adapter: solid_cable
  silence_polling: true
  polling_interval: 0.1.seconds

test:
  adapter: test

production:
  adapter: solid_cable
  silence_polling: true
  polling_interval: 1.second
